[package]
name = "rust_example"
version = "0.1.0"
authors = ["James Lee <jameslee@goodeffect.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
